### ISSUE TITLE
The version on plugin website is not this one

### ISSUE THREAD

**Issue by bao-qian** [Wox-launcher/Wox.Plugin.Switcheroo#1]
https://www.getwox.com/plugin/52
It seems like @lances101 maintaining a more recent version.
I suggest add @lances101 as the Collaborators for this repo.

**Comment by qianlifeng** [comment]
@lances101 would you like to put your Switcheroo version be part of Wox-launcher organazation?

**Comment by lances101** [comment]
@qianlifeng, Sure! Although I have no idea how to do it without having admin rights in the @Wox-launcher organization.

**Comment by bao-qian** [comment]
@lances101 you are one of the Collaborators of **this** repo now and have admin permission for this repo.
You can commit your changes to this repo, and maybe also made some changes in the [plugin website](https://www.getwox.com/plugin/52)

**Comment by lances101** [comment]
@happlebao I can either make a pull-request from my repo to this one, merge and maintain it here **or** change the ownership of my repo itself, but then @qianlifeng 's repo has to be renamed. You decide.

**Comment by bao-qian** [comment]
@lances101 I think the first option (maintain it here) would be better.

**Comment by lances101** [comment]
Done. I'll delete my fork so that there is no confusion.
