### ISSUE TITLE
When settings the action key to * it does not come up in search result. 

### ISSUE THREAD

**Issue by eleijonmarck** [Wox-launcher/Wox.Plugin.Switcheroo#3]

**Comment by eleijonmarck** [comment]
I would love to have this as a default feature in Wox.

**Comment by lances101** [comment]
Could you provide more info? I've tried setting the hotkey of Switcheroo to \* and it does work (last three results are from Switcheroo)
![image](https://cloud.githubusercontent.com/assets/4784785/13528521/c10082d6-e216-11e5-9439-363bb986449c.png)

**Comment by eleijonmarck** [comment]
Ah, I see. It was so far down in the search results. Is there a way to arrange the search criteria? In order to make all of the Switcheroos results to get to the top each time?

**Comment by eleijonmarck** [comment]
I guess I have to make all the other plugins to act on other keys to make my wish come true. But that would be my workaround for getting the way of Wox that I think it is meant to be.
@lances101 great work guys! I love it. Its exactly what you need in windows for keeping of the mouse.

**Comment by lances101** [comment]
Well, yes, you could make a special keybind for Switcheroo through the Hotkeys tab in settings and that would always return you the right thing. Not the most ideal solution, but better than nothing for the moment.
