### ISSUE TITLE
Don't work with wox version 1.2.813

### ISSUE THREAD

**Issue by roose** [Wox-launcher/Wox.Plugin.Switcheroo#4]
Log: 2016-04-17 01:43:35.2986|ERROR|Wox.Infrastructure.Logger.Log|Switcheroo for Wox : Couldn't load plugin

**Comment by lances101** [comment]
Looking into it now.

**Comment by lances101** [comment]
Wox.Infrastructure library was updated in a way that broke Switcheroo, because it relied on some functionality that changed. I'm fixing Switcheroo now.

**Comment by lances101** [comment]
Updated the Switcheroo plugin. It should now work with the latest versions of Wox. 
@roose, please try reinstalling the plugin and tell me how it goes.

**Comment by roose** [comment]
@lances101 thank you very much :ok_hand:
